### ISSUE TITLE
Alternative languages do not get rendered

### ISSUE THREAD

**Issue by linawolf** [TYPO3-Documentation/render-guides#357]

**Comment by garvinhicking** [comment]
OK, today I worked on this in depth, and of course it wasn't as easy as I had hoped.

# Previously on.... 

## Then: Sphinx

The main issue is that the Sphinx-based rendering structure kept localized documentation INSIDE the main Documentation, e.g.:

`/Documentation/Index.rst` (english)
`/Documentation/Localization.de_DE/Index.rst` (german)
`/Documentation/Localization.ru_RU/Index.rst` (russian)

The rendered output would then be:

`/Documentation-GENERATED-temp/Index.html` (english)
`/Documentation-GENERATED-temp/Localization.de_DE/Index.rst` (german)
`/Documentation-GENERATED-temp/Localization.ru_RU/Index.rst` (russian)

Each Localization directory has it's own "Settings.cfg", it's own "Includes.rst.txt" etc. and thus it's own scope, for reference:  https://github.com/TYPO3-Documentation/TYPO3CMS-Tutorial-GettingStarted/tree/12.4/Documentation/Localization.ru_RU

That would get published to: https://docs.typo3.org/m/typo3/tutorial-getting-started/12.4/ru-ru/

And its inventory: https://docs.typo3.org/m/typo3/tutorial-getting-started/12.4/ru-ru/objects.inv.json

So even though each sub-documentation is its own distinct guide, it is all kept in one large root directory where the ENGLISH documentation is also in.

And, sadly, the Localization subdirectories use _includes_ in the format of `/Localization.ru_RU/Includes.rst` - so they are NOT placed relative to their own root, but to the main root. This means we cannot just render `Documentation/Localization.ru_RU` as the input directory, because all references will then fail. I don't see how we could automatically rewrite all "absolute" links to match, and we can't really pressure users into rewriting all their documentation to change their links to relative ones (`/Includes.rst`).

## Now: phpdocumentor/guides

The guides binary works like this: It checks on a base directory like `Documentation`. It searches for the entrypoint (like Index.rst). Then it "crawls" that file for everything it finds. "Orphaned" documents currently are ignored. So if you have a `FAQ.rst` file, if you don't link it, it won't get rendered, and no error will occur.

This is why the localization files would be recognized as orphans, as they are not linked to from the main Index entrypoint. This is wanted, because of course Localizations are distinct from the root project's english base variant.

## Enter: TYPO3-Documentation/render-guides

Via https://github.com/TYPO3-Documentation/render-guides/pull/351 our `render-guides` actually filters out all these files with an `PostCollectFilesForParsingEvent` event listener, so that they are not recognized as orphans. And also discarded from the render pipeline.

# What we want

So what we actually want to do (as to my understanding) is this:

* First Step (We have this now):
  * Start the rendering process from `Documentation/`
  * Crawl all "normal links"
  * Ignore those pesky `Localization.*` directories
  * Render all of this to `Documentation-GENERATED-temp`
  * Our objects.inv will only contain the `en_US` documentation now.
  * "English documentation" is now finished. We don't want to modify the rendered result anymore for the ENGLISH variant now.
* Second step (THIS IS MISSING)
  * Recognize that we may have `Localization.*` directories in place
  * For each found localization directory, start a sub-process rendering this documentation.
  * This needs to recognize its own `guides.xml` file, it's own `Includes.rst`.
  * This should happen within the same PHP process run that Step 1 was in, we do NOT want to launch multiple render commands (due to our current pipeline process and because directories are dynamic, and we wouldn't want users to perform steps on every sub-documentation directory)
  * The result of the rendering shall be... 
    * **merged** into the existing `Documentation-GENERATED-temp`
    * ... **BUT** into a subdirectory: `Documentation-GENERATED-temp/Localization.ru_RU`
    * ... and NOT overwrite the root /objects.inv file
    * ... and NOT remove any of the other root files that already were rendered for `en_US`
    * ... and NOT be orphan-filtered by the implemented Event listener

I've created a PR for this: https://github.com/TYPO3-Documentation/render-guides/pull/362

This one works on the level of the Run Decorator. After the main rendering it just executes sub-renderings by rewiring the vital input options/arguments:

* **input-file**: Will be set to the entrypoint like `Localization.ru_RU/Index.rst`
* **input**: Remains set to `Documentation` (because this dictates the "project root" it can **not** be set to `Documentation/Localization.ru_RU` because then all absolute links will not resolve to the proper project root)
* **input-format**: Depending on the entrypoint will be set to RST or MD, because maybe localizations use a different format
* **output**: Set to a subdirectory like `Documentation-GENERATED-temp/Localization.ru_RU`

Sadly that seems a bit too hacky-ish. Executing the command again like this will not re-trigger the asset-collection of files to be rendered. Also it won't re-trigger the `PostCollectFilesForParsingEvent` event (which would then need to NOT discard the localization files in case a localization is rendered).

# Help?

My main problem is that I don't have enough core knowledge about the rendering process of `guides`. So I don't know how we can achieve this "sub-processing" properly, which would let us post-process Localization directories and merge into a subdirectory of the initial result, and let it be a distinct output.

Any thoughts on this? :-)

**Comment by linawolf** [comment]
Thanks a lot for solving this, @garvinhicking !
